rabbitmq:
  host: localhost
  virtual-host: rabbitmq-host
  user:
    exchange-name: user-amq-exchange
    student:
      queue-name: student-queue
    teacher:
      queue-name: teacher-queue
  admission:
    exchange-name: admission-amq-exchange
    queue-name: admission-queue
